Sync with upstream
rdo-common/openstack-tripleo-ui-deps pull request #8
Opened 2017-03-22 12:47 UTC by honza

* Add redux-form (MIT)
* Remove karma, jasmine, and phantomjs

2017-03-22 12:47 UTC, honza commented
@apevec @hguemar

2017-03-22 17:35 UTC, apevec commented on openstack-tripleo-ui-deps.spec
> -Requires:       phantomjs >= 1.9.7
How come this dep is gone, can you link to upstream where it was removed?

2017-03-22 17:37 UTC, apevec requested changes

2017-03-22 17:37 UTC, apevec commented on openstack-tripleo-ui-deps.spec
> +* Wed Mar 22 2017 Honza Pokorny <honza@redhat.com> 7-2
Release: field was not bumped to 2

2017-03-22 17:37 UTC, apevec commented on openstack-tripleo-ui-deps.spec
> +
nitpick: please remote this empty line

2017-03-22 23:04 UTC, honza commented on openstack-tripleo-ui-deps.spec
> -Requires:       phantomjs >= 1.9.7
It was removed in [this commit](https://github.com/openstack/tripleo-ui/commit/0376dfe55f487abcec517ea1ec512f58a5bd27ec).

2017-03-23 01:55 UTC, apevec approved these changes

2017-03-23 01:56 UTC, merged